NAME :K.SRINIVAS
ROLL :235229139
CLASS:MSA DATA SCIENCE

Bank Management System Using Python And Mysql

In [1]:
import mysql.connector

# Connect to the MySQL database
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",  # Provide your MySQL password here
    database="bank"
)

cursor = conn.cursor()

bankname = input("Enter Your Bank Name:")
print("Your Bank:", bankname)

def create_account(account_number, first_name, last_name, balance):
    try:
        cursor.execute("INSERT INTO Customer (Account_Number, First_Name, Last_Name, Balance) VALUES (%s, %s, %s, %s)",
                       (account_number, first_name, last_name, balance))
        conn.commit()
        print("Account created successfully.")
    except Exception as e:
        print(f"Error creating account: {str(e)}")

def deposit(account_number, amount):
    try:
        cursor.execute("UPDATE Customer SET Balance = Balance + %s WHERE Account_Number = %s",
                       (amount, account_number))
        cursor.execute("INSERT INTO Transaction (Account_Number, TransactionType, Amount) VALUES (%s, 'Deposit', %s)",
                       (account_number, amount))
        conn.commit()
        print("Deposit successful.")
    except Exception as e:
        print(f"Error making a deposit: {str(e)}")

def withdraw(account_number, amount):
    try:
        cursor.execute("UPDATE Customer SET Balance = Balance - %s WHERE Account_Number = %s",
                       (amount, account_number))
        cursor.execute("INSERT INTO Transaction (Account_Number, TransactionType, Amount) VALUES (%s, 'Withdrawal', %s)",
                       (account_number, amount))
        conn.commit()
        print("Withdrawal successful.")
    except Exception as e:
        print(f"Error making a withdrawal: {str(e)}")

def check_balance(account_number):
    cursor.execute("SELECT Balance FROM Customer WHERE Account_Number = %s", (account_number,))
    row = cursor.fetchone()
    if row:
        balance = row[0]
        print(f"Account Balance: {balance}")
    else:
        print("Account not found.")

def delete_account(account_number, first_name, last_name, balance):
    try:
        cursor.execute("DELETE FROM Customer WHERE Account_Number = %s AND First_Name = %s AND Last_Name = %s AND Balance = %s",
                       (account_number, first_name, last_name, balance))
        conn.commit()
        print("Account Deleted successfully.")
    except Exception as e:
        print(f"Error deleting account: {str(e)}")

def main():
    while True:
        print("\nBank Management System")
        print("1. Create Account")
        print("2. Deposit")
        print("3. Withdraw")
        print("4. Check Balance")
        print("5. Exit")
        print("6. Delete your account")

        choice = input("Enter your choice: ")

        if choice == '1':
            account_number = input("Enter account number: ")
            first_name = input("Enter first name: ")
            last_name = input("Enter last name: ")
            balance = float(input("Enter initial balance: "))
            create_account(account_number, first_name, last_name, balance)
        elif choice == '2':
            account_number = input("Enter account number: ")
            amount = float(input("Enter deposit amount: "))
            deposit(account_number, amount)
        elif choice == '3':
            account_number = input("Enter account number: ")
            amount = float(input("Enter withdrawal amount: "))
            withdraw(account_number, amount)
        elif choice == '4':
            account_number = input("Enter account number: ")
            check_balance(account_number)
        elif choice == '5':
            print("Thank you for visiting:", bankname)
            conn.close()
            break
        elif choice == '6':
            account_number = input("Enter account number: ")
            first_name = input("Enter first name: ")
            last_name = input("Enter last name: ")
            delete_account(account_number, first_name, last_name, balance)
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

C:\Users\kodin\anaconda3\lib\site-packages\mysql\connector\abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':
C:\Users\kodin\anaconda3\lib\site-packages\mysql\connector\abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 No connection could be made because the target machine actively refused it)